#!/usr/bin/env python3
"""Apply canonicals, Open Graph / Twitter tags, robots.txt and sitemap.xml.

Chrome is duplicated per page rather than templated, so doing this by hand across
20-odd files guarantees drift. This walks public/, derives each page's tags from
its own <title> and description, and writes robots.txt and sitemap.xml from the
same page list — so the sitemap cannot list a page that does not exist.

Idempotent. Re-run after adding a page.

Usage:
  python3 scripts/build-seo.py
"""

from __future__ import annotations

import html
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"

SITE = "https://kisalafilms-website.elombe.workers.dev"
SHARE_IMAGE = f"{SITE}/images/brand/kisala-films-logo.png"

# Kept out of the index. /thanks.html and /wrap-quote/ are post-conversion and
# ad-campaign pages; styleguide and 404 have no business in search results.
NOINDEX = {
  "thanks.html",
  "deposit-thanks.html",
  "styleguide.html",
  "404.html",
  "wrap-quote/index.html",
}

# Priority by role rather than a flat list: the conversion path first.
PRIORITY = {
    "index.html": "1.0",
    "wrap-studio.html": "0.9",
    "pricing.html": "0.9",
    "services.html": "0.8",
    "gallery.html": "0.8",
    "shop.html": "0.8",
    "shop/wrap.html": "0.8",
    "shop/photoshoot.html": "0.7",
    "shop/merch.html": "0.7",
    "locations/jersey-city.html": "0.8",
    "locations/brooklyn.html": "0.8",
    "locations/new-york-city.html": "0.8",
}
DEFAULT_PRIORITY = "0.6"


def is_redirect_stub(page: str) -> bool:
    return "http-equiv" in page and 'content="0;' in page.replace("'", '"')


def canonical_path(rel: str) -> str:
    """The URL Cloudflare actually serves the page at.

    Workers Static Assets strips the .html and 307-redirects /pricing.html to
    /pricing. Canonicals and sitemap entries therefore have to be extensionless:
    pointing them at the .html form makes every one of them a redirect, which is
    the opposite of what a canonical is for.

    Verified against `wrangler dev`, including /locations — which resolves to
    locations.html even though a locations/ directory sits beside it.
    """
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel.removesuffix(".html")


def read_title(page: str) -> str:
    match = re.search(r"<title>(.*?)</title>", page, re.S)
    return html.unescape(match.group(1).strip()) if match else "Kisala Films"


def read_description(page: str) -> str:
    match = re.search(r'<meta name="description" content="(.*?)"\s*/?>', page, re.S)
    return html.unescape(match.group(1).strip()) if match else ""


def strip_existing(page: str) -> str:
    """Remove the tags this script owns, so re-running cannot double them up.

    Each pattern takes the tag's whole line including its newline. Leaving the
    newline behind is a fixed point rather than unbounded growth — strip 13 tags,
    leave 13 blank lines, insert 13 back — so it never breaks anything and never
    stops, it just permanently pads every <head> on the site with dead space.
    """
    patterns = [
        r'[ \t]*<link rel="canonical"[^>]*>\n',
        r'[ \t]*<meta property="og:[^"]+"[^>]*>\n',
        r'[ \t]*<meta name="twitter:[^"]+"[^>]*>\n',
        r'[ \t]*<meta name="robots"[^>]*>\n',
        r"[ \t]*<!-- SEO: generated by scripts/build-seo\.py -->\n",
    ]
    for pattern in patterns:
        page = re.sub(pattern, "", page)
    return page


def build_tags(rel: str, title: str, description: str) -> str:
    url = SITE + canonical_path(rel)
    esc = html.escape
    lines = ["  <!-- SEO: generated by scripts/build-seo.py -->"]

    if rel in NOINDEX:
        # No canonical on a noindex page — it would only invite indexing.
        lines.append('  <meta name="robots" content="noindex, nofollow">')
    else:
        lines.append(f'  <link rel="canonical" href="{url}">')

    lines += [
        '  <meta property="og:type" content="website">',
        '  <meta property="og:site_name" content="Kisala Films">',
        f'  <meta property="og:title" content="{esc(title, quote=True)}">',
        f'  <meta property="og:url" content="{url}">',
        f'  <meta property="og:image" content="{SHARE_IMAGE}">',
        '  <meta name="twitter:card" content="summary_large_image">',
        f'  <meta name="twitter:title" content="{esc(title, quote=True)}">',
        f'  <meta name="twitter:image" content="{SHARE_IMAGE}">',
    ]
    if description:
        lines.insert(4, f'  <meta property="og:description" content="{esc(description, quote=True)}">')
        lines.append(f'  <meta name="twitter:description" content="{esc(description, quote=True)}">')

    return "\n".join(lines) + "\n"


def apply_to(path: Path) -> str:
    rel = path.relative_to(PUBLIC).as_posix()
    page = path.read_text(encoding="utf-8")
    if is_redirect_stub(page):
        return "skipped (redirect stub)"

    original = page
    page = strip_existing(page)
    tags = build_tags(rel, read_title(page), read_description(page))

    anchor = '  <link rel="stylesheet" href="/css/carsy.css">'
    if anchor in page:
        page = page.replace(anchor, tags + anchor, 1)
    elif "</head>" in page:
        page = page.replace("</head>", tags + "</head>", 1)
    else:
        return "FAILED (no <head>)"

    if page == original:
        return "unchanged"
    path.write_text(page, encoding="utf-8")
    return "noindex" if rel in NOINDEX else "indexed"


def write_robots(indexable: list[str]) -> None:
    disallow = "\n".join(f"Disallow: {canonical_path(rel)}" for rel in sorted(NOINDEX))
    (PUBLIC / "robots.txt").write_text(
        "# Kisala Films\n"
        "# Generated by scripts/build-seo.py — edit that, not this.\n"
        "\n"
        "User-agent: *\n"
        "Allow: /\n"
        f"{disallow}\n"
        "\n"
        f"Sitemap: {SITE}/sitemap.xml\n",
        encoding="utf-8",
    )


def write_sitemap(indexable: list[str]) -> None:
    today = date.today().isoformat()
    entries = "\n".join(
        f"  <url>\n"
        f"    <loc>{SITE}{canonical_path(rel)}</loc>\n"
        f"    <lastmod>{today}</lastmod>\n"
        f"    <priority>{PRIORITY.get(rel, DEFAULT_PRIORITY)}</priority>\n"
        f"  </url>"
        for rel in indexable
    )
    (PUBLIC / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- Generated by scripts/build-seo.py — re-run it after adding a page. -->\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{entries}\n"
        "</urlset>\n",
        encoding="utf-8",
    )


def main() -> None:
    indexable: list[str] = []

    for path in sorted(PUBLIC.rglob("*.html")):
        rel = path.relative_to(PUBLIC).as_posix()
        result = apply_to(path)
        print(f"{rel:36} {result}")
        if result not in {"FAILED (no <head>)", "skipped (redirect stub)"} and rel not in NOINDEX:
            indexable.append(rel)

    # Sort by priority so the conversion path leads the file, then by path.
    indexable.sort(key=lambda r: (-float(PRIORITY.get(r, DEFAULT_PRIORITY)), r))

    write_robots(indexable)
    write_sitemap(indexable)
    print(f"\nrobots.txt and sitemap.xml written — {len(indexable)} indexable pages")


if __name__ == "__main__":
    main()
