#!/usr/bin/env python3
"""Generate the shop hub, collection pages, and product pages.

Chrome is duplicated per page across this site rather than templated, so these
are composed from shop.html's header/footer/<head> and written out as static
files — the same approach build-local-pages.py uses for city landings.

Data:
  public/data/shop-catalog.json  — collections, wrap finishes, photoshoot pkgs
  public/data/products.json      — merch drop

Outputs:
  public/shop.html
  public/shop/{photoshoot,wrap,merch}.html
  public/shop/photoshoot/*.html
  public/shop/wrap/*.html
  public/shop/merch/*.html

Usage:
  python3 scripts/build-shop-pages.py
"""

from __future__ import annotations

import html
import json
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
SOURCE = PUBLIC / "shop.html"
OUTDIR = PUBLIC / "shop"
CATALOG = PUBLIC / "data" / "shop-catalog.json"
PRODUCTS = PUBLIC / "data" / "products.json"
SITE = "https://kisalafilms-website.elombe.workers.dev"

INHERITED = [
    r'[ \t]*<!-- JSON-LD: generated by scripts/build-jsonld\.mjs -->\s*<script type="application/ld\+json">[\s\S]*?</script>\n',
    r'[ \t]*<script type="application/ld\+json">[\s\S]*?</script>\n',
    r'[ \t]*<!-- SEO: generated by scripts/build-seo\.py -->\n',
    r'[ \t]*<link rel="canonical"[^>]*>\n',
    r'[ \t]*<meta property="og:[^"]+"[^>]*>\n',
    r'[ \t]*<meta name="twitter:[^"]+"[^>]*>\n',
    r'[ \t]*<meta name="robots"[^>]*>\n',
]


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def chrome() -> tuple[str, str, str]:
    raw = SOURCE.read_text(encoding="utf-8")
    head = re.search(r"<!DOCTYPE html>.*?<head>\n(.*?)</head>", raw, re.S)
    header = re.search(r"(<header class=\"site-header\">.*?</aside>\s*)", raw, re.S)
    footer = re.search(r"(<footer class=\"site-footer\">.*?</html>\s*)", raw, re.S)
    if not (head and header and footer):
        raise SystemExit("Could not read the chrome out of shop.html")
    return head.group(1), header.group(1), footer.group(1)


def head_for(title: str, description: str, head_template: str) -> str:
    head = head_template
    for pattern in INHERITED:
        head = re.sub(pattern, "", head)
    # Scripts are re-inserted by page_shell so they cannot stack across rebuilds.
    head = re.sub(r'[ \t]*<script src="/js/kisala-config\.js"></script>\n', "", head)
    head = re.sub(r'[ \t]*<script src="/js/analytics\.js"></script>\n', "", head)
    head = re.sub(r"<title>.*?</title>", f"<title>{esc(title)}</title>", head, flags=re.S)
    return re.sub(
        r'<meta name="description" content=".*?">',
        f'<meta name="description" content="{esc(description)}">',
        head,
        flags=re.S,
    )


def breadcrumbs(*crumbs: tuple[str, str]) -> str:
    items = []
    for i, (name, path) in enumerate(crumbs, start=1):
        url = SITE + path if path != "/" else SITE + "/"
        items.append(
            f"""          {{
            "@type": "ListItem",
            "position": {i},
            "name": {json.dumps(name)},
            "item": {json.dumps(url)}
          }}"""
        )
    return f"""  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@graph": [
      {{
        "@type": "BreadcrumbList",
        "itemListElement": [
{',\n'.join(items)}
        ]
      }}
    ]
  }}
  </script>
"""


def page_shell(
    *,
    title: str,
    description: str,
    head_template: str,
    header: str,
    body: str,
    footer: str,
    crumbs: list[tuple[str, str]],
    extra_scripts: str = "",
) -> str:
    # Footer block from chrome() includes scripts through </html>. Strip the
    # trailing scripts so we can re-add a consistent set, then append extras.
    footer_only = re.sub(
        r"\n  <script src=.*?</html>\s*\Z",
        "\n",
        footer,
        flags=re.S,
    )
    scripts = (
        '  <script src="/js/config-apply.js"></script>\n'
        '  <script src="/js/nav.js"></script>\n'
        '  <script src="/js/site.js"></script>\n'
        f"{extra_scripts}"
        "</body>\n</html>\n"
    )
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        f"{head_for(title, description, head_template)}"
        f"{breadcrumbs(*crumbs)}"
        '  <script src="/js/kisala-config.js"></script>\n'
        '  <script src="/js/analytics.js"></script>\n'
        "</head>\n"
        '<body class="carsy">\n\n'
        f"{header.rstrip()}\n\n"
        f"{body.lstrip()}\n"
        f"{footer_only.rstrip()}\n"
        f"{scripts}"
    )


def collection_cards(catalog: dict) -> str:
    cards = []
    for c in catalog["collections"]:
        cards.append(
            f"""        <a class="shop-collection-card" href="/shop/{esc(c['slug'])}">
          <div class="shop-collection-shot">
            <img src="{esc(c['image'])}" alt="" width="900" height="600" loading="lazy">
            <span class="shop-collection-eyebrow">{esc(c['eyebrow'])}</span>
          </div>
          <div class="shop-collection-body">
            <h2 class="h3">{esc(c['title'])}</h2>
            <p class="p">{esc(c['tagline'])}</p>
            <span class="link-arrow">{esc(c['cta'])} &rarr;</span>
          </div>
        </a>"""
        )
    return "\n".join(cards)


def hub_body(catalog: dict) -> str:
    return f"""  <section class="page-hero">
    <div class="container">
      <p class="eyebrow">Shop</p>
      <h1>Three ways in.</h1>
      <p class="p-lg">Photoshoot packages, vinyl finishes, and the WLG merch drop. Pick a collection — each one opens into its own products.</p>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="shop-collection-grid">
{collection_cards(catalog)}
      </div>
    </div>
  </section>
"""


def photoshoot_collection_body(items: list[dict]) -> str:
    cards = []
    for p in items:
        if p.get("priceCfg"):
            price_html = f'Starting at <span data-cfg="{esc(p["priceCfg"])}">{esc(p["priceLabel"].split("at ",1)[-1])}</span>'
        else:
            price_html = esc(p["priceLabel"])
        cards.append(
            f"""        <a class="look-card shop-product-card" href="/shop/photoshoot/{esc(p['slug'])}">
          <div class="look-shot">
            <span class="look-kind">{esc(p['kind'])}</span>
            <img src="{esc(p['image'])}" alt="{esc(p['title'])}" width="800" height="1000" loading="lazy">
          </div>
          <div class="look-body">
            <div class="look-head">
              <h2 class="h3">{esc(p['title'])}</h2>
              <span class="look-price">{price_html}</span>
            </div>
            <p class="look-blurb">{esc(p['blurb'])}</p>
            <p class="look-reserve"><span class="link-arrow">View package &rarr;</span></p>
          </div>
        </a>"""
        )
    return f"""  <section class="page-hero">
    <div class="container">
      <p class="eyebrow"><a href="/shop">Shop</a> / Photoshoot</p>
      <h1>Photoshoot</h1>
      <p class="p-lg">The bike gets filmed the same way it gets wrapped. Transformation film, stills, and film-only packages.</p>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="lookbook-grid">
{chr(10).join(cards)}
      </div>
    </div>
  </section>
"""


def photoshoot_product_body(p: dict) -> str:
    includes = "\n".join(f"          <li>{esc(x)}</li>" for x in p["includes"])
    gallery = "\n".join(
        f'          <img src="{esc(src)}" alt="" width="640" height="400" loading="lazy">'
        for src in p["gallery"]
    )
    if p.get("priceCfg"):
        price_html = f'Starting at <span data-cfg="{esc(p["priceCfg"])}">{esc(p["priceLabel"].split("at ",1)[-1])}</span>'
    else:
        price_html = esc(p["priceLabel"])
    return f"""  <section class="page-hero page-hero--compact">
    <div class="container">
      <p class="eyebrow"><a href="/shop">Shop</a> / <a href="/shop/photoshoot">Photoshoot</a> / {esc(p['title'])}</p>
      <h1>{esc(p['title'])}</h1>
      <p class="p-lg">{esc(p['blurb'])}</p>
    </div>
  </section>

  <section class="section">
    <div class="container detail-split">
      <div>
        <img src="{esc(p['image'])}" alt="{esc(p['title'])}" width="900" height="600" loading="eager">
      </div>
      <div>
        <p class="eyebrow">{esc(p['kind'])}</p>
        <p class="tier-price">{price_html}</p>
        <p class="p">{esc(p['detail'])}</p>
        <ul class="include-list">
{includes}
        </ul>
        <div class="btn-row">
          <a class="btn btn-primary" href="{esc(p['studioHref'])}" data-track="cta_click" data-track-label="shop-photoshoot-{esc(p['slug'])}">Build this shoot</a>
          <a class="btn btn-secondary" href="/gallery">See the gallery</a>
        </div>
      </div>
    </div>
  </section>

  <section class="section section-muted">
    <div class="container">
      <div class="section-head">
        <p class="eyebrow">In frame</p>
        <h2>How it looks</h2>
      </div>
      <div class="thumb-grid">
{gallery}
      </div>
    </div>
  </section>
"""


def wrap_card(w: dict) -> str:
    chips = "".join(
        f'<span class="wheel-finish-chip" style="background:{esc(c["hex"])}" title="{esc(c["name"])}"></span>'
        for c in w["colors"][:4]
    )
    coverage = "".join(f"<li>{esc(x)}</li>" for x in w["coverage"])
    price = (
        f'Starting at <span data-cfg="{esc(w["startingFromCfg"])}">{esc(w["startingLabel"].split("at ",1)[-1])}</span>'
        if w.get("startingFromCfg")
        else esc(w["startingLabel"])
    )
    return f"""        <a class="wheel-card" href="/shop/wrap/{esc(w['slug'])}">
          <div class="wheel-card-media">
            <img src="{esc(w['heroImage'])}" alt="{esc(w['title'])} vinyl finish" width="800" height="800" loading="lazy">
          </div>
          <div class="wheel-card-body">
            <p class="wheel-card-series">{esc(w['series'])}</p>
            <h2 class="wheel-card-title">{esc(w['title'])}</h2>
            <p class="wheel-card-tagline">{esc(w['tagline'])}</p>
            <ul class="wheel-card-sizes">{coverage}</ul>
            <p class="wheel-card-price">{price}</p>
            <div class="wheel-card-finishes">
              {chips}
              <span class="wheel-card-finish-count">{esc(w['finishCount'])}</span>
            </div>
          </div>
        </a>"""


def wrap_collection_body(items: list[dict]) -> str:
    cards = "\n".join(wrap_card(w) for w in items)
    return f"""  <section class="page-hero">
    <div class="container">
      <p class="eyebrow"><a href="/shop">Shop</a> / Wrap</p>
      <h1>Vinyl finishes</h1>
      <p class="p-lg">Seven finishes, presented like a wheel line. Pick a finish, see featured colours and bikes, then open Wrap Studio with it already selected.</p>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="wheel-grid">
{cards}
      </div>
    </div>
  </section>
"""


def wrap_product_body(w: dict, siblings: list[dict]) -> str:
    coverage = "\n".join(f"            <li>{esc(x)}</li>" for x in w["coverage"])
    colors = "\n".join(
        f"""          <figure class="wheel-color-card">
            <img src="{esc(c['image'])}" alt="{esc(c['name'])}" width="400" height="400" loading="lazy">
            <figcaption>
              <strong>{esc(c['name'])}</strong>
              <span>{esc(c['vendor'])}</span>
            </figcaption>
          </figure>"""
        for c in w["colors"]
    )
    bikes = "\n".join(
        f'          <img src="{esc(src)}" alt="" width="640" height="400" loading="lazy">'
        for src in w["bikeGallery"]
    )
    price = (
        f'Starting at <span data-cfg="{esc(w["startingFromCfg"])}">{esc(w["startingLabel"].split("at ",1)[-1])}</span>'
        if w.get("startingFromCfg")
        else esc(w["startingLabel"])
    )
    studio = f"/wrap-studio?finish={quote(w['finishParam'])}"
    others = "\n".join(
        f'          <a class="wheel-mini" href="/shop/wrap/{esc(s["slug"])}">'
        f'<span class="finish-swatch {esc(s["swatchClass"])}" aria-hidden="true"></span>'
        f'<span>{esc(s["title"])}</span></a>'
        for s in siblings
        if s["slug"] != w["slug"]
    )
    return f"""  <section class="wheel-pdp">
    <div class="container wheel-pdp-grid">
      <div class="wheel-pdp-media">
        <div class="wheel-pdp-hero">
          <img src="{esc(w['heroImage'])}" alt="{esc(w['title'])} vinyl wrap film" width="1000" height="1000" loading="eager">
        </div>
      </div>
      <div class="wheel-pdp-buy">
        <p class="eyebrow"><a href="/shop">Shop</a> / <a href="/shop/wrap">Wrap</a></p>
        <p class="wheel-card-series">{esc(w['series'])}</p>
        <h1>{esc(w['title'])}</h1>
        <p class="wheel-card-price wheel-pdp-price">{price}</p>
        <p class="p-lg">{esc(w['tagline'])}</p>
        <p class="p">{esc(w['detail'])}</p>
        <div class="wheel-pdp-block">
          <h2 class="h6">Coverage</h2>
          <ul class="wheel-card-sizes">
{coverage}
          </ul>
        </div>
        <div class="wheel-pdp-block">
          <h2 class="h6">Catalogue</h2>
          <p class="p">{esc(w['finishCount'])} in the Metro Restyling feed — search the exact film in Wrap Studio.</p>
        </div>
        <div class="btn-row">
          <a class="btn btn-primary" href="{studio}" data-track="cta_click" data-track-label="shop-wrap-{esc(w['slug'])}">Build with {esc(w['title'])}</a>
          <a class="btn btn-secondary" href="/gallery">See it on bikes</a>
        </div>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="section-head">
        <p class="eyebrow">Film gallery</p>
        <h2>{esc(w['title'])} colours</h2>
        <p class="p-lg">Featured films in this finish. Screens lie about colour — real swatches come with the quote.</p>
      </div>
      <div class="wheel-color-grid">
{colors}
      </div>
    </div>
  </section>

  <section class="section section-muted">
    <div class="container">
      <div class="section-head">
        <p class="eyebrow">On the bike</p>
        <h2>Vehicle gallery</h2>
      </div>
      <div class="thumb-grid">
{bikes}
      </div>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="section-head">
        <p class="eyebrow">More finishes</p>
        <h2>Explore the line</h2>
      </div>
      <div class="wheel-mini-row">
{others}
      </div>
    </div>
  </section>
"""


def merch_collection_body(drop: dict, products: list[dict]) -> str:
    cards = []
    for p in products:
        kind = "Tee" if p["kind"] == "tee" else "Hoodie"
        cards.append(
            f"""        <a class="look-card shop-product-card" href="/shop/merch/{esc(p['id'])}" data-filter-item="{esc(p['kind'])}">
          <div class="look-shot">
            <span class="look-kind">{kind}</span>
            <img src="{esc(p['images']['hero'])}" alt="{esc(p['title'])} in {esc(p['color'])}" width="800" height="1000" loading="lazy">
            <img src="{esc(p['images']['detail01'])}" alt="" width="800" height="1000" loading="lazy" aria-hidden="true">
          </div>
          <div class="look-body">
            <div class="look-head">
              <h2 class="h3">{esc(p['title'])}</h2>
              <span class="look-price">${p['price']}</span>
            </div>
            <p class="look-quote">{esc(p['quote'])}</p>
            <p class="look-colour"><span class="look-dot" style="background:{esc(p['colorHex'])}"></span>{esc(p['color'])}</p>
            <p class="look-blurb">{esc(p['blurb'])}</p>
            <p class="look-reserve"><span class="link-arrow">View piece &rarr;</span></p>
          </div>
        </a>"""
        )
    options = "\n".join(
        f'            <option value="{esc(p["title"])} — {esc(p["color"])} (${p["price"]})">'
        f'{esc(p["title"])} &mdash; {esc(p["color"])} (${p["price"]})</option>'
        for p in products
    )
    return f"""  <section class="page-hero">
    <div class="container">
      <p class="eyebrow"><a href="/shop">Shop</a> / Merch</p>
      <h1>{esc(drop.get('drop', 'Merch'))}</h1>
      <p class="p-lg">Eight pieces carrying the lines that keep the garage moving. Heavyweight cotton and midweight fleece, Kisala Films mark on the front, the quote across the back left shoulder.</p>
      <p class="p">No cart and no checkout &mdash; this is a limited run, so you reserve a piece and I confirm sizing and payment directly.</p>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="filter-tabs" data-filter-tabs>
        <button type="button" class="on" data-filter="all">Everything</button>
        <button type="button" data-filter="tee">Tees</button>
        <button type="button" data-filter="hoodie">Hoodies</button>
      </div>
      <div class="lookbook-grid">
{chr(10).join(cards)}
      </div>
    </div>
  </section>

  <section class="section section-muted reveal" id="reserve">
    <div class="container book-grid">
      <div>
        <p class="eyebrow">Reserve a piece</p>
        <h2>First run, cut to order</h2>
        <p class="p-lg">Tell me which piece and what size. I&rsquo;ll come back to confirm the run, the fit, and how to pay &mdash; nothing is charged from this page.</p>
      </div>
      <form class="form" action="https://formsubmit.co/elombe@swftstudios.com" method="POST" accept-charset="UTF-8">
        <input type="hidden" name="_subject" value="Kisala Films - merch reservation">
        <input type="hidden" name="_template" value="table">
        <input type="hidden" name="_captcha" value="false">
        <input type="hidden" name="_next" value="{SITE}/shop/merch?sent=1#reserve">
        <input type="text" name="_honey" value="" tabindex="-1" autocomplete="off" aria-hidden="true" style="display:none !important" inputmode="none">
        <div class="fld">
          <label for="piece">Piece</label>
          <select id="piece" name="piece" data-reserve-select required>
            <option value="">Select a piece</option>
{options}
          </select>
        </div>
        <div class="fld">
          <label for="size">Size</label>
          <select id="size" name="size" required>
            <option value="">Select size</option>
            <option value="S">S</option>
            <option value="M">M</option>
            <option value="L">L</option>
            <option value="XL">XL</option>
            <option value="2XL">2XL</option>
            <option value="Not sure">Not sure &mdash; help me pick</option>
          </select>
        </div>
        <div class="fld"><label for="shop-name">Name</label><input id="shop-name" name="name" type="text" autocomplete="name" required></div>
        <div class="fld"><label for="shop-email">Email</label><input id="shop-email" name="email" type="email" autocomplete="email" required></div>
        <div class="fld"><label for="shop-notes">Anything else? <span class="fld-hint">optional</span></label><textarea id="shop-notes" name="notes" rows="3"></textarea></div>
        <button class="btn btn-primary" type="submit">Reserve my piece</button>
        <p class="form-note">Thanks &mdash; I&rsquo;ll confirm the run and your size.</p>
      </form>
    </div>
  </section>
"""


def merch_product_body(p: dict, products: list[dict]) -> str:
    kind = "Tee" if p["kind"] == "tee" else "Hoodie"
    piece_val = f"{p['title']} — {p['color']} (${p['price']})"
    options = "\n".join(
        f'            <option value="{esc(x["title"])} — {esc(x["color"])} (${x["price"]})"'
        f'{" selected" if x["id"] == p["id"] else ""}>'
        f'{esc(x["title"])} &mdash; {esc(x["color"])} (${x["price"]})</option>'
        for x in products
    )
    return f"""  <section class="page-hero page-hero--compact">
    <div class="container">
      <p class="eyebrow"><a href="/shop">Shop</a> / <a href="/shop/merch">Merch</a> / {esc(p['title'])}</p>
      <h1>{esc(p['title'])}</h1>
      <p class="p-lg">{esc(p['quote'])}</p>
    </div>
  </section>

  <section class="section">
    <div class="container detail-split">
      <div class="look-shot look-shot--pdp">
        <span class="look-kind">{kind}</span>
        <img src="{esc(p['images']['hero'])}" alt="{esc(p['title'])} in {esc(p['color'])}" width="800" height="1000" loading="eager">
        <img src="{esc(p['images']['detail01'])}" alt="" width="800" height="1000" loading="lazy" aria-hidden="true">
      </div>
      <div>
        <p class="tier-price">${p['price']}</p>
        <p class="look-colour"><span class="look-dot" style="background:{esc(p['colorHex'])}"></span>{esc(p['color'])}</p>
        <p class="p">{esc(p['blurb'])}</p>
        <p class="p">Limited first run. Reserve below — I confirm sizing and payment directly. Nothing is charged from this page.</p>
        <div class="btn-row">
          <a class="btn btn-primary" href="#reserve" data-reserve="{esc(piece_val)}">Reserve yours</a>
          <a class="btn btn-secondary" href="/shop/merch">All merch</a>
        </div>
      </div>
    </div>
  </section>

  <section class="section section-muted" id="reserve">
    <div class="container book-grid">
      <div>
        <p class="eyebrow">Reserve</p>
        <h2>{esc(p['title'])}</h2>
        <p class="p">Pick a size and leave your details. I&rsquo;ll come back to confirm.</p>
        <div class="thumb-grid" style="grid-template-columns:repeat(2,1fr)">
          <img src="{esc(p['images']['detail01'])}" alt="" width="400" height="500" loading="lazy">
          <img src="{esc(p['images']['detail02'])}" alt="" width="400" height="500" loading="lazy">
        </div>
      </div>
      <form class="form" action="https://formsubmit.co/elombe@swftstudios.com" method="POST" accept-charset="UTF-8">
        <input type="hidden" name="_subject" value="Kisala Films - merch reservation">
        <input type="hidden" name="_template" value="table">
        <input type="hidden" name="_captcha" value="false">
        <input type="hidden" name="_next" value="{SITE}/shop/merch/{esc(p['id'])}?sent=1#reserve">
        <input type="text" name="_honey" value="" tabindex="-1" autocomplete="off" aria-hidden="true" style="display:none !important" inputmode="none">
        <div class="fld">
          <label for="piece">Piece</label>
          <select id="piece" name="piece" data-reserve-select required>
            <option value="">Select a piece</option>
{options}
          </select>
        </div>
        <div class="fld">
          <label for="size">Size</label>
          <select id="size" name="size" required>
            <option value="">Select size</option>
            <option value="S">S</option>
            <option value="M">M</option>
            <option value="L">L</option>
            <option value="XL">XL</option>
            <option value="2XL">2XL</option>
            <option value="Not sure">Not sure &mdash; help me pick</option>
          </select>
        </div>
        <div class="fld"><label for="shop-name">Name</label><input id="shop-name" name="name" type="text" autocomplete="name" required></div>
        <div class="fld"><label for="shop-email">Email</label><input id="shop-email" name="email" type="email" autocomplete="email" required></div>
        <div class="fld"><label for="shop-notes">Anything else? <span class="fld-hint">optional</span></label><textarea id="shop-notes" name="notes" rows="3"></textarea></div>
        <button class="btn btn-primary" type="submit">Reserve my piece</button>
        <p class="form-note">Thanks &mdash; I&rsquo;ll confirm the run and your size.</p>
      </form>
    </div>
  </section>
"""


def write(path: Path, content: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    prev = path.read_text(encoding="utf-8") if path.exists() else None
    path.write_text(content, encoding="utf-8")
    if prev == content:
        return "unchanged"
    return "wrote" if prev is None else "updated"


def main() -> None:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    merch_data = json.loads(PRODUCTS.read_text(encoding="utf-8"))
    products = merch_data["products"]
    head_t, header, footer = chrome()

    # Patch footer "Shop the drop" to stay on /shop
    footer = footer.replace('href="/shop">Shop the drop', 'href="/shop">Shop')

    results = []

    # Hub
    hub = page_shell(
        title="Shop — Photoshoot, Wrap & Merch | Kisala Films",
        description="Shop Kisala Films: photoshoot packages, vinyl wrap finishes, and the WLG merch drop.",
        head_template=head_t,
        header=header,
        body=hub_body(catalog),
        footer=footer,
        crumbs=[("Home", "/"), ("Shop", "/shop")],
    )
    results.append((SOURCE, write(SOURCE, hub)))

    # Photoshoot collection
    path = OUTDIR / "photoshoot.html"
    results.append(
        (
            path,
            write(
                path,
                page_shell(
                    title="Photoshoot — Shop | Kisala Films",
                    description="Transformation film, photo sets, and film-only packages from the Kisala Films garage.",
                    head_template=head_t,
                    header=header,
                    body=photoshoot_collection_body(catalog["photoshoot"]),
                    footer=footer,
                    crumbs=[("Home", "/"), ("Shop", "/shop"), ("Photoshoot", "/shop/photoshoot")],
                ),
            ),
        )
    )

    for p in catalog["photoshoot"]:
        path = OUTDIR / "photoshoot" / f"{p['slug']}.html"
        results.append(
            (
                path,
                write(
                    path,
                    page_shell(
                        title=f"{p['title']} — Photoshoot | Kisala Films",
                        description=p["blurb"],
                        head_template=head_t,
                        header=header,
                        body=photoshoot_product_body(p),
                        footer=footer,
                        crumbs=[
                            ("Home", "/"),
                            ("Shop", "/shop"),
                            ("Photoshoot", "/shop/photoshoot"),
                            (p["title"], f"/shop/photoshoot/{p['slug']}"),
                        ],
                    ),
                ),
            )
        )

    # Wrap collection
    path = OUTDIR / "wrap.html"
    results.append(
        (
            path,
            write(
                path,
                page_shell(
                    title="Vinyl Wrap Finishes — Shop | Kisala Films",
                    description="Cast vinyl finishes presented like a wheel line — gloss, satin, matte, metallic, colour shift, chrome and textured.",
                    head_template=head_t,
                    header=header,
                    body=wrap_collection_body(catalog["wrap"]),
                    footer=footer,
                    crumbs=[("Home", "/"), ("Shop", "/shop"), ("Wrap", "/shop/wrap")],
                ),
            ),
        )
    )

    for w in catalog["wrap"]:
        path = OUTDIR / "wrap" / f"{w['slug']}.html"
        results.append(
            (
                path,
                write(
                    path,
                    page_shell(
                        title=f"{w['title']} Vinyl Wrap — Shop | Kisala Films",
                        description=w["tagline"] + " " + w["detail"],
                        head_template=head_t,
                        header=header,
                        body=wrap_product_body(w, catalog["wrap"]),
                        footer=footer,
                        crumbs=[
                            ("Home", "/"),
                            ("Shop", "/shop"),
                            ("Wrap", "/shop/wrap"),
                            (w["title"], f"/shop/wrap/{w['slug']}"),
                        ],
                    ),
                ),
            )
        )

    # Merch collection
    path = OUTDIR / "merch.html"
    results.append(
        (
            path,
            write(
                path,
                page_shell(
                    title=f"Merch — {merch_data.get('drop', 'WLG Quotes')} | Kisala Films",
                    description="The WLG Quotes first run — heavyweight tees and midweight fleece. Reserve a piece before the run is cut.",
                    head_template=head_t,
                    header=header,
                    body=merch_collection_body(merch_data, products),
                    footer=footer,
                    crumbs=[("Home", "/"), ("Shop", "/shop"), ("Merch", "/shop/merch")],
                    extra_scripts='  <script src="/js/shop.js"></script>\n',
                ),
            ),
        )
    )

    for p in products:
        path = OUTDIR / "merch" / f"{p['id']}.html"
        results.append(
            (
                path,
                write(
                    path,
                    page_shell(
                        title=f"{p['title']} — Merch | Kisala Films",
                        description=f"{p['title']} in {p['color']}. {p['quote']}",
                        head_template=head_t,
                        header=header,
                        body=merch_product_body(p, products),
                        footer=footer,
                        crumbs=[
                            ("Home", "/"),
                            ("Shop", "/shop"),
                            ("Merch", "/shop/merch"),
                            (p["title"], f"/shop/merch/{p['id']}"),
                        ],
                        extra_scripts='  <script src="/js/shop.js"></script>\n',
                    ),
                ),
            )
        )

    for path, status in results:
        print(f"  {status:9} {path.relative_to(ROOT)}")
    print(f"\n{len(results)} shop pages.")


if __name__ == "__main__":
    main()
