/**
 * Inject JSON-LD into the pages that warrant it.
 *
 * Written in Node rather than Python so it can execute kisala-config.js and
 * config-apply.js directly and ask them for the active prices. The structured
 * data therefore cannot drift from what the page displays — flip pricingMode and
 * the Offer markup moves with everything else.
 *
 * What it asserts is limited to what the site can stand behind: the business
 * name, the Jersey City locality, the email, the published hours,
 * appointment-only, and the three served areas. No aggregateRating, no review
 * markup, no street address, no telephone, no invented credentials.
 *
 * Idempotent. Re-run after editing prices, the FAQ or the page set.
 *
 * Usage:
 *   node scripts/build-jsonld.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");
const SITE = "https://kisalafilms-website.elombe.workers.dev";

const MARK_OPEN = "  <!-- JSON-LD: generated by scripts/build-jsonld.mjs -->";

/* ---- Ask the real config for the real prices ---------------------------- */
function loadConfig() {
  const sandbox = {
    window: {},
    console,
    // config-apply.js walks the DOM on load. There is no DOM here, and no page
    // to hydrate — only its resolver is wanted.
    document: {
      querySelectorAll: () => [],
      createElement: () => ({ dataset: {} }),
    },
  };
  sandbox.globalThis = sandbox;

  const context = vm.createContext(sandbox);
  for (const file of ["kisala-config.js", "config-apply.js"]) {
    vm.runInContext(readFileSync(join(PUBLIC, "js", file), "utf8"), context, { filename: file });
  }
  return { raw: sandbox.window.KISALA_CONFIG, api: sandbox.window.KisalaConfig };
}

const { raw: CONFIG, api: RESOLVER } = loadConfig();

const GARAGE_ID = `${SITE}/#garage`;

/** The one business node every page points at, rather than restating it. */
const garage = () => ({
  "@type": "AutoBodyShop",
  "@id": GARAGE_ID,
  name: "Kisala Films",
  description:
    "Motorcycle wrap film and transformation film, by appointment, from a one-person garage in Jersey City, NJ.",
  url: `${SITE}/`,
  email: CONFIG.email,
  image: `${SITE}/images/brand/kisala-films-logo.png`,
  sameAs: [CONFIG.instagram],
  address: {
    "@type": "PostalAddress",
    addressLocality: CONFIG.garage.city,
    addressRegion: CONFIG.garage.region,
    addressCountry: CONFIG.garage.country,
  },
  areaServed: CONFIG.zones
    .filter((z) => z.available && z.page)
    .map((z) => ({ "@type": "City", name: z.id === "nyc" ? "New York" : z.short })),
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      opens: "10:00",
      closes: "18:00",
    },
  ],
  ...(CONFIG.garage.appointmentOnly ? { publicAccess: false } : {}),
});

/**
 * Cloudflare Static Assets serves these extensionless and 307-redirects the
 * .html form, so structured data has to name the URL that actually resolves.
 * Kept in step with canonical_path() in scripts/build-seo.py.
 */
const url = (path) => SITE + (path === "/" ? "/" : path.replace(/\.html$/, ""));

const breadcrumbs = (trail) => ({
  "@type": "BreadcrumbList",
  itemListElement: trail.map(([name, path], i) => ({
    "@type": "ListItem",
    position: i + 1,
    name,
    item: url(path),
  })),
});

/* ---- FAQ, read off the page so the two cannot disagree ------------------ */
function readFaq(html) {
  const items = [...html.matchAll(
    /<button class="faq-q"[^>]*>(.*?)<span class="mark">.*?<\/button>\s*<p class="faq-a">(.*?)<\/p>/gs
  )];
  return items.map(([, q, a]) => [plain(q), plain(a)]);
}

/** Markup and entities out: JSON-LD has to be plain text. */
function plain(text) {
  return text
    .replace(/<[^>]+>/g, "")
    .replace(/&mdash;/g, "—")
    .replace(/&ndash;/g, "–")
    .replace(/&rsquo;/g, "\u2019")
    .replace(/&lsquo;/g, "\u2018")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const faqPage = (pairs) => ({
  "@type": "FAQPage",
  mainEntity: pairs.map(([name, answer]) => ({
    "@type": "Question",
    name,
    acceptedAnswer: { "@type": "Answer", text: answer },
  })),
});

/* ---- Offers, priced from the live config ------------------------------- */
function offer(key, name, description) {
  const price = RESOLVER.servicePrice(key);
  return {
    "@type": "Service",
    name,
    description,
    serviceType: name,
    provider: { "@id": GARAGE_ID },
    areaServed: CONFIG.zones.filter((z) => z.available && z.page).map((z) => ({
      "@type": "City",
      name: z.id === "nyc" ? "New York" : z.short,
    })),
    offers: {
      "@type": "Offer",
      priceCurrency: "USD",
      // A range, because the real number depends on the bike. lowPrice is what
      // the page quotes as "from".
      priceSpecification: {
        "@type": "PriceSpecification",
        priceCurrency: "USD",
        minPrice: price.low,
        maxPrice: price.high,
      },
      availability: "https://schema.org/LimitedAvailability",
    },
  };
}

/* ---- Per-page graphs --------------------------------------------------- */
const PAGES = {
  "index.html": () => [
    garage(),
    {
      "@type": "WebSite",
      "@id": `${SITE}/#website`,
      url: `${SITE}/`,
      name: "Kisala Films",
      publisher: { "@id": GARAGE_ID },
    },
  ],

  "faq.html": (html) => [
    garage(),
    faqPage(readFaq(html)),
    breadcrumbs([["Home", "/"], ["FAQ", "/faq.html"]]),
  ],

  "pricing.html": () => [
    garage(),
    offer("fullWrap", "Full colour-change motorcycle wrap", "Every painted panel in premium cast film, fairings off, edges wrapped."),
    offer("partialWrap", "Partial motorcycle wrap and accents", "Tank, tail, belly pan or stripes in cast film."),
    offer("chromeDelete", "Motorcycle chrome delete", "Trim, badges and brightwork in gloss or satin black."),
    offer("tankGuard", "Motorcycle tank protection film", "Clear film over the knee and buckle wear zones."),
    breadcrumbs([["Home", "/"], ["Pricing", "/pricing.html"]]),
  ],

  "services.html": () => [
    garage(),
    breadcrumbs([["Home", "/"], ["Services", "/services.html"]]),
  ],

  "gallery.html": () => [breadcrumbs([["Home", "/"], ["Gallery", "/gallery.html"]])],
  "about.html": () => [
    garage(),
    breadcrumbs([["Home", "/"], ["About", "/about.html"]]),
  ],
  "locations.html": () => [
    garage(),
    breadcrumbs([["Home", "/"], ["Locations", "/locations.html"]]),
  ],
  "contact.html": () => [
    garage(),
    breadcrumbs([["Home", "/"], ["Contact", "/contact.html"]]),
  ],
  "journal.html": () => [breadcrumbs([["Home", "/"], ["Journal", "/journal.html"]])],
  "testimonials.html": () => [breadcrumbs([["Home", "/"], ["Rider notes", "/testimonials.html"]])],
  "shop.html": () => [breadcrumbs([["Home", "/"], ["Shop", "/shop.html"]])],
  "wrap-studio.html": () => [
    garage(),
    breadcrumbs([["Home", "/"], ["Wrap Studio", "/wrap-studio.html"]]),
  ],

  "services/full-wraps.html": () => [
    offer("fullWrap", "Full colour-change motorcycle wrap", "Every painted panel in premium cast film, fairings off, edges wrapped."),
    breadcrumbs([["Home", "/"], ["Services", "/services.html"], ["Full colour-change wraps", "/services/full-wraps.html"]]),
  ],
  "services/accent-package.html": () => [
    offer("partialWrap", "Partial motorcycle wrap and accents", "Tank, tail, belly pan or stripes in cast film."),
    breadcrumbs([["Home", "/"], ["Services", "/services.html"], ["Partial & accents", "/services/accent-package.html"]]),
  ],
  "services/transformation-film.html": () => [
    breadcrumbs([["Home", "/"], ["Services", "/services.html"], ["Transformation film", "/services/transformation-film.html"]]),
  ],
};

/* ---- Write ------------------------------------------------------------- */
function block(graph) {
  const payload = JSON.stringify({ "@context": "https://schema.org", "@graph": graph }, null, 2)
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n");
  // No trailing newline: the anchor line's own newline terminates it, which is
  // what keeps a re-run from gaining a blank line each time.
  return `${MARK_OPEN}\n  <script type="application/ld+json">\n${payload}\n  </script>`;
}

/**
 * Strip a previous run's block so re-running cannot stack them up.
 *
 * Takes the block's own trailing newline with it and leaves the anchor line's
 * newline alone, so strip and insert are exact inverses. Getting that wrong is
 * silent: the page still renders, it just grows a blank line per build.
 */
function stripExisting(html) {
  return html.replace(
    /[ \t]*<!-- JSON-LD: generated by scripts\/build-jsonld\.mjs -->\s*<script type="application\/ld\+json">[\s\S]*?<\/script>\n/g,
    ""
  );
}

let count = 0;
for (const [rel, build] of Object.entries(PAGES)) {
  const path = join(PUBLIC, rel);
  let html = stripExisting(readFileSync(path, "utf8"));

  const graph = build(html);
  const anchor = '  <link rel="stylesheet" href="/css/carsy.css">';
  if (!html.includes(anchor)) {
    console.error(`${rel}: no stylesheet anchor, skipped`);
    continue;
  }

  html = html.replace(anchor, `${anchor}\n${block(graph)}`, 1);
  writeFileSync(path, html, "utf8");

  const types = graph.map((n) => n["@type"]);
  console.log(`${rel.padEnd(36)} ${types.join(", ")}`);
  count += 1;
}

console.log(`\n${count} pages carry JSON-LD (pricing mode: ${RESOLVER.mode})`);
